version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    container_name: product_catalog_service-mysql
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: productcatalogservice
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
    volumes:
        - /home/arun/secrets:/run/secrets
        - mysql_data:/var/lib/mysql
    ports:
        - "3306:3306"

volumes:
  mysql_data: